name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Flutter Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # cache: true # Optional: Enable caching

      - name: Install Flutter dependencies
        run: flutter pub get
        # If your project is in a subdirectory, e.g. 'my_app', uncomment and set:
        # working-directory: ./my_app

      # Optional: Clean Flutter project (can sometimes resolve caching issues)
      # - name: Clean Flutter project
      #   run: flutter clean
      #   # working-directory: ./my_app

      - name: Build Debug APK
        run: flutter build apk --debug # Changed from --release to --debug
        # If your project is in a subdirectory, e.g. 'my_app', uncomment and set:
        # working-directory: ./my_app

      - name: Upload Debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk # Changed artifact name for clarity
          path: build/app/outputs/flutter-apk/app-debug.apk # Changed path to app-debug.apk
          if-no-files-found: error # Fails the step if the APK is not found
