name: Build Flutter Android APK

on:
  push:
    branches:
      - main # Or your default branch, e.g., master
  pull_request:
    branches:
      - main # Or your default branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Or 'zulu', 'adopt', etc.
          java-version: '17'     # Flutter often requires Java 11 or 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0' # <-- IMPORTANT: Replace with your project's Flutter version
          channel: 'stable'
          cache: true # Highly recommended for faster builds

      - name: Get Flutter dependencies
        run: flutter pub get

      # Optional: Clean previous builds if necessary
      # - name: Clean Flutter build
      #   run: flutter clean

      - name: Build APK
        run: flutter build apk --release
        # To build a debug APK, use: flutter build apk --debug
        # To build an appbundle for Play Store, use: flutter build appbundle --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          # If you built a debug APK, the path would be:
          # path: build/app/outputs/flutter-apk/app-debug.apk
          # If you built an appbundle, the path would be:
          # path: build/app/outputs/bundle/release/app-release.aab